# -*- coding: utf-8 -*-
"""dictionaries.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Rbx-REqY09BbFMK6us3EPWoA_2gLhqNY
"""

import random
t=tuple(random.sample(range(1,10),5))
t1=tuple(sorted(t))
print(t)
print(t1)
k=int(input("Enter value for k - "))
print(t1[0:k],t1[:-k-1:-1])

capital={'Karnataka':'Bangalore','Maharashtra':'Mumbai',}
capital.keys()
capital.values()
capital.items()
capital.get('Karnataka')
print(capital)
other_capital={'Gujarat':'Ahmedabad'}
capital.update(other_capital)
print(capital)
print(other_capital)

capital={'Karnataka':'Bangalore','Maharashtra':'Mumbai',}
capital.get('Karnataka')

def print_items(dictionary):
    for key, value in dictionary.items():
        print(f"Username: {key}, Password: {value}")

def print_keys(dictionary):
    for key in dictionary.keys():
        print(key)

def print_values(dictionary):
    for i in dictionary:
        print(dictionary[i])

def get_password(username, dictionary):
    if username in dictionary:
        return dictionary[username]
    else:
        return "Username not found"

def change_password(username, new_password, dictionary):
    if username in dictionary:
        dictionary[username] = new_password
        return "Password updated successfully"
    else:
        return "Username not found"


passwd = {'rahul': 'genius', 'kumar': 'smart', 'ankita': 'intelligent'}


print("Items in the dictionary:")
print_items(passwd)
print()


print("Keys in the dictionary:")
print_keys(passwd)
print()


print("Values in the dictionary:")
print_values(passwd)
print()


username = 'rahul'
password = get_password(username, passwd)
print(f"Password for '{username}': {password}")
print()


username = 'ankita'
new_password = 'brilliant'
result = change_password(username, new_password, passwd)
print(result)
print()


print("Items in the dictionary:")
print_items(passwd)

def print_values(dictionary):
    for i in dictionary:
        print(i)
passwd = {'rahul': 'genius', 'kumar': 'smart', 'ankita': 'intelligent'}
print_values(passwd)

def add_entry(dictionary):
    word = input("Enter the word: ")
    meaning = input("Enter the meaning: ")
    dictionary[word] = meaning
    print("Entry added successfully.")

def search_word(dictionary):
    word = input("Enter the word to search: ")
    if word in dictionary:
        print(f"Meaning of '{word}': {dictionary[word]}")
    else:
        print(f"'{word}' not found in the dictionary.")

def search_meaning(dictionary):
    meaning = input("Enter the meaning to search: ")
    words = [word for word, mean in dictionary.items() if mean == meaning]
    if words:
        print(f"Words with meaning '{meaning}':")
        for word in words:
            print(word)
    else:
        print(f"No words found with meaning '{meaning}'.")

def remove_entry(dictionary):
    word = input("Enter the word to remove: ")
    if word in dictionary:
        del dictionary[word]
        print(f"'{word}' entry removed successfully.")
    else:
        print(f"'{word}' not found in the dictionary.")

def display_sorted(dictionary):
    sorted_words = sorted(dictionary.keys())
    print("Words in the dictionary (sorted alphabetically):")
    for word in sorted_words:
        print(f"Word: {word}, Meaning: {dictionary[word]}")

dictionary = {}

while True:
    print("\nMenu:")
    print("1. Add an entry")
    print("2. Search for a word")
    print("3. Search for a meaning")
    print("4. Remove an entry")
    print("5. Display all words sorted alphabetically")
    print("6. Quit")

    choice = input("Enter your choice (1-6): ")

    if choice == '1':
        add_entry(dictionary)
    elif choice == '2':
        search_word(dictionary)
    elif choice == '3':
        search_meaning(dictionary)
    elif choice == '4':
        remove_entry(dictionary)
    elif choice == '5':
        display_sorted(dictionary)
    elif choice == '6':
        print("Exiting the program...")
        break
    else:
        print("Invalid choice. Please try again.")

